### ISSUE TITLE
add Entry comments

### ISSUE THREAD

**Issue by selectthegang** [repldex/Repldex#149]
allow people to comment on entries, but require the user to be logged in with Discord so then fellow admins can ban their access!

**Comment by leon332157** [comment]
test webhook

**Comment by leon332157** [comment]
test1

**Comment by mat-1** [comment]
Should this work like Wikipedia talk pages? Wikipedia talk pages are to discuss modifications to articles though, but that might be better.

**Comment by selectthegang** [comment]
Yes

**Comment by selectthegang** [comment]
Removing this issue
