### ISSUE TITLE
Store entry content as markdown

### ISSUE THREAD

**Issue by Codemonkey51** [repldex/Repldex#155]
Right now we store it as html, but that is a pain to deal with. Markdown can be easily converted to html easily with libraries. Markdown is also much more versatile.

**Comment by selectthegang** [comment]
I don't know how i'll be able to add the markdown on the application, dm me a link that contains information how to add markdown into a android app created with Kotlin over on Discord.

**Comment by selectthegang** [comment]
This would be a great way to prevent XSS on v3

**Comment by mat-1** [comment]
Changed in v3.
