### ISSUE TITLE
Request editor status

### ISSUE THREAD

**Issue by whippingdot** [repldex/Repldex#205]
Add me and @IronCladDev please (⊙_⊙;)

**Comment by selectthegang** [comment]
I'm pretty sure they aren't accepting new editors at this time due to v3 being worked on.

**Comment by whippingdot** [comment]
> I'm pretty sure they aren't accepting new editors at this time due to v3 being worked on.

I am happy if you add me to the repo, but I meant an entry for us

**Comment by whippingdot** [comment]
Isn't that bad. If anyone can create an entry **without review** some weird entries could be added.

**Comment by selectthegang** [comment]
We will obviously be adding some auto moderation and trust factors. So, people with a good trust level will be able to create/edit entries. People with a bad trust level will not be able to contribute to the project until they work that level up.

**Comment by whippingdot** [comment]
Done close the issue!

**Comment by selectthegang** [comment]
Glad to help!
