### ISSUE TITLE
Migrate config to db

### ISSUE THREAD

**Issue by Codemonkey51** [repldex/Repldex#22]
Allow a config option to hold all user data (roles) in a db, for allowing edits on the fly (when hosted on repl)

this would allow ppl running repldex to have an add/remove editor/admin command, and have less file clutter.

Some other features would probably depend on this (admin panel for roles, easily add and remove people) and a few others up coming features, also it would allow someone to give a user admin and let them add/remove editors without:
a) having repl edit perms 
or 
b) not having access to the users vm or computer.

**Comment by Codemonkey51** [comment]
This could also come with a migration tool like migrate.py to auto set some stuff up

**Comment by mat-1** [comment]
But the reason I made config as its own file is so I can change stuff like the prefix without having to touch any other files or having to create a new database

**Comment by mat-1** [comment]
Wait nvm I read the issue wrong, I agree.

**Comment by mat-1** [comment]
Btw instead of having a new collection for that, we should store whether a user is an editor/admin/etc in the already existing `users` collection

**Comment by jetstream0** [comment]
#96 will start a config collection in the db. However @mat-1 @Codemonkey51 I worry migrating config to db will complicate testing for contributors who do not have access to the db, so the effort should be done at the same time as the `mock-db` branch

**Comment by jetstream0** [comment]
Or after... and update mock-db

**Comment by jetstream0** [comment]
config collection in db made

**Comment by selectthegang** [comment]
This would most likely have to be required as we are planning to not have it hosted on a repl.

**Comment by Codemonkey51** [comment]
Addressed in v3
