### ISSUE TITLE
Contribution ideas 

### ISSUE THREAD

**Issue by Codemonkey51** [repldex/Repldex#58]
here is a list of ideas for new contributors (you can get cool discord rank for contributing)

- [ ] Improve ui
- [ ] Add new commands/features
- [ ] Make repldex easier to use
- [ ] Fix bugs

**Comment by leon332157** [comment]
I think there's a few things we can do to make contributing easier:
- There should be a database server/mock database for contributing only, which makes testing easier. 
- With the above being said, this allows local testing of the website and bot which isn't dependent on the database if the mock server was implemented. 
- Unit test to work with the mock server. (This is worth considering but isn't as important)

So I think the the most immediate solution is by finishing an API server and make the website, the bot and the database 3 different applications.

**Comment by Codemonkey51** [comment]
> I think there's a few things we can do to make contributing easier:
> 
> * There should be a database server/mock database for contributing only, which makes testing easier.
> * With the above being said, this allows local testing of the website and bot which isn't dependent on the database if the mock server was implemented.
> * Unit test to work with the mock server. (This is worth considering but isn't as important)
> 
> So I think the the most immediate solution is by finishing an API server and make the website, the bot and the database 3 different applications.

Hello! So I agree, we have 2 of these in their own separate issues #39 is for unit tests, and #35 for api.

Right now the bot and website can be hosted separately but we should definitely work on a testing version of database.py (one that has hard coded answers) so that testing the website/ bot can be made easier without having to setup mongo db. Also for separating them more that could be added to config.json (let users choose server bot or both, and testing mode or live database )

**Comment by leon332157** [comment]
I'm working on re-organizing the repo into something that's easier to contribute with. I will make a pull request later. Another suggestion is that if we are decided on using poetry for package management, we should keep the lock file instead of ignoring it.

**Comment by Codemonkey51** [comment]
> I'm working on re-organizing the repo into something that's easier to contribute with. I will make a pull request later. Another suggestion is that if we are decided on using poetry for package management, we should keep the lock file instead of ignoring it.

One idea I had was to split the server into a module so it would be server.api, server.admin all that, and to maybe move all of discord bot into a module

**Comment by jetstream0** [comment]
I'm working on featured articles and a guide page

**Comment by mat-1** [comment]
These ideas should be made into individual detailed issues

**Comment by Codemonkey51** [comment]
Outdated, v3 will address ui, and the rest should be separate issues if anyone wants them done or added.
